image: docker:git
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  GRAFANA_VERSION: "4.6"

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

development:
  stage: deploy
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" ${GRAFANA_VERSION}
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

testing:
  stage: deploy
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}" ${GRAFANA_VERSION}
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}"
  only:
    - branches
  except:
    - master

stable:
  stage: deploy
  script:
    - export VERSION=$(grep ' VERSION' ${GRAFANA_VERSION}/Dockerfile|awk -F" " '{ print $3 }')
    - echo ${VERSION}
    - docker build -t "$CI_REGISTRY_IMAGE:v${VERSION}" ${GRAFANA_VERSION}
    - docker push "$CI_REGISTRY_IMAGE:v${VERSION}"
  only:
    - tags
